# Site settings
title: ShenFei's Site
email: shenfei1208@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I can because i think i can.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: None
github_username:  samuel1208

# Build settings
markdown: kramdown

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
